/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CategoryIndexImport } from './routes/$category/index'
import { Route as ProductsProductImport } from './routes/products.$product'
import { Route as CategoriesSplatImport } from './routes/categories.$'
import { Route as CategorySubCategoryIndexImport } from './routes/$category/$subCategory/index'
import { Route as CategorySubCategoryProductIndexImport } from './routes/$category/$subCategory/$product/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CategoryIndexRoute = CategoryIndexImport.update({
  id: '/$category/',
  path: '/$category/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsProductRoute = ProductsProductImport.update({
  id: '/products/$product',
  path: '/products/$product',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesSplatRoute = CategoriesSplatImport.update({
  id: '/categories/$',
  path: '/categories/$',
  getParentRoute: () => rootRoute,
} as any)

const CategorySubCategoryIndexRoute = CategorySubCategoryIndexImport.update({
  id: '/$category/$subCategory/',
  path: '/$category/$subCategory/',
  getParentRoute: () => rootRoute,
} as any)

const CategorySubCategoryProductIndexRoute =
  CategorySubCategoryProductIndexImport.update({
    id: '/$category/$subCategory/$product/',
    path: '/$category/$subCategory/$product/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/categories/$': {
      id: '/categories/$'
      path: '/categories/$'
      fullPath: '/categories/$'
      preLoaderRoute: typeof CategoriesSplatImport
      parentRoute: typeof rootRoute
    }
    '/products/$product': {
      id: '/products/$product'
      path: '/products/$product'
      fullPath: '/products/$product'
      preLoaderRoute: typeof ProductsProductImport
      parentRoute: typeof rootRoute
    }
    '/$category/': {
      id: '/$category/'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof CategoryIndexImport
      parentRoute: typeof rootRoute
    }
    '/$category/$subCategory/': {
      id: '/$category/$subCategory/'
      path: '/$category/$subCategory'
      fullPath: '/$category/$subCategory'
      preLoaderRoute: typeof CategorySubCategoryIndexImport
      parentRoute: typeof rootRoute
    }
    '/$category/$subCategory/$product/': {
      id: '/$category/$subCategory/$product/'
      path: '/$category/$subCategory/$product'
      fullPath: '/$category/$subCategory/$product'
      preLoaderRoute: typeof CategorySubCategoryProductIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories/$': typeof CategoriesSplatRoute
  '/products/$product': typeof ProductsProductRoute
  '/$category': typeof CategoryIndexRoute
  '/$category/$subCategory': typeof CategorySubCategoryIndexRoute
  '/$category/$subCategory/$product': typeof CategorySubCategoryProductIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories/$': typeof CategoriesSplatRoute
  '/products/$product': typeof ProductsProductRoute
  '/$category': typeof CategoryIndexRoute
  '/$category/$subCategory': typeof CategorySubCategoryIndexRoute
  '/$category/$subCategory/$product': typeof CategorySubCategoryProductIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/categories/$': typeof CategoriesSplatRoute
  '/products/$product': typeof ProductsProductRoute
  '/$category/': typeof CategoryIndexRoute
  '/$category/$subCategory/': typeof CategorySubCategoryIndexRoute
  '/$category/$subCategory/$product/': typeof CategorySubCategoryProductIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories/$'
    | '/products/$product'
    | '/$category'
    | '/$category/$subCategory'
    | '/$category/$subCategory/$product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories/$'
    | '/products/$product'
    | '/$category'
    | '/$category/$subCategory'
    | '/$category/$subCategory/$product'
  id:
    | '__root__'
    | '/'
    | '/categories/$'
    | '/products/$product'
    | '/$category/'
    | '/$category/$subCategory/'
    | '/$category/$subCategory/$product/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesSplatRoute: typeof CategoriesSplatRoute
  ProductsProductRoute: typeof ProductsProductRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
  CategorySubCategoryIndexRoute: typeof CategorySubCategoryIndexRoute
  CategorySubCategoryProductIndexRoute: typeof CategorySubCategoryProductIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesSplatRoute: CategoriesSplatRoute,
  ProductsProductRoute: ProductsProductRoute,
  CategoryIndexRoute: CategoryIndexRoute,
  CategorySubCategoryIndexRoute: CategorySubCategoryIndexRoute,
  CategorySubCategoryProductIndexRoute: CategorySubCategoryProductIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/categories/$",
        "/products/$product",
        "/$category/",
        "/$category/$subCategory/",
        "/$category/$subCategory/$product/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/categories/$": {
      "filePath": "categories.$.tsx"
    },
    "/products/$product": {
      "filePath": "products.$product.tsx"
    },
    "/$category/": {
      "filePath": "$category/index.tsx"
    },
    "/$category/$subCategory/": {
      "filePath": "$category/$subCategory/index.tsx"
    },
    "/$category/$subCategory/$product/": {
      "filePath": "$category/$subCategory/$product/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
