/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CheckoutImport } from './routes/checkout'
import { Route as IndexImport } from './routes/index'
import { Route as ProductsProductImport } from './routes/products.$product'
import { Route as CategoriesSplatImport } from './routes/categories.$'

// Create/Update Routes

const CheckoutRoute = CheckoutImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsProductRoute = ProductsProductImport.update({
  id: '/products/$product',
  path: '/products/$product',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesSplatRoute = CategoriesSplatImport.update({
  id: '/categories/$',
  path: '/categories/$',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutImport
      parentRoute: typeof rootRoute
    }
    '/categories/$': {
      id: '/categories/$'
      path: '/categories/$'
      fullPath: '/categories/$'
      preLoaderRoute: typeof CategoriesSplatImport
      parentRoute: typeof rootRoute
    }
    '/products/$product': {
      id: '/products/$product'
      path: '/products/$product'
      fullPath: '/products/$product'
      preLoaderRoute: typeof ProductsProductImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/categories/$': typeof CategoriesSplatRoute
  '/products/$product': typeof ProductsProductRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/categories/$': typeof CategoriesSplatRoute
  '/products/$product': typeof ProductsProductRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/categories/$': typeof CategoriesSplatRoute
  '/products/$product': typeof ProductsProductRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkout' | '/categories/$' | '/products/$product'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout' | '/categories/$' | '/products/$product'
  id: '__root__' | '/' | '/checkout' | '/categories/$' | '/products/$product'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  CategoriesSplatRoute: typeof CategoriesSplatRoute
  ProductsProductRoute: typeof ProductsProductRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  CategoriesSplatRoute: CategoriesSplatRoute,
  ProductsProductRoute: ProductsProductRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/checkout",
        "/categories/$",
        "/products/$product"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/checkout": {
      "filePath": "checkout.tsx"
    },
    "/categories/$": {
      "filePath": "categories.$.tsx"
    },
    "/products/$product": {
      "filePath": "products.$product.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
